server:
  port: 8140 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI4GKs2Rvce8gnWRc3sTg2
    keySecret: N4eGmB80KaeoNM3wNwEH5bUv54f4Dn
    bucketName: hobo-hobo