server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-core # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.136.128:33306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  redis:
    host: 192.168.136.128
    port: 6389
    database: 0
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
  #开启Feign对Sentinel的支持
  #feign:
  sentinel:
    enabled: true
mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/srb/core/mapper/xml/*.xml

# 设置日志级别
#logging:
#  level:
#    root: ERROR
wx:
  open:
    # 微信开放平台 appid
    appId: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    appSecret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
    redirectUri: http://guli.shop/api/wx/callback8110
logging:
  level:
    com.atguigu.srb.core.client.OssFileClient: debug #以什么级别监控哪个接口